apiVersion: kubernetes-client.io/v1	
kind: ExternalSecret	
metadata:	
  name: auth-redis	
spec:	
  backendType: vault	
  vaultMountPoint: kubernetes	
  vaultRole: jx-vault
  data:
    - name: redis-password	
      key: secret/data/{{ .Values.secretPaths.redis }}
      property: redis-password	
