filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: auth
releases:
- chart: ./charts/auth-istio
  version: 0.0.5
  name: auth-istio
  values:
  - jx-values.yaml
- chart: ./charts/keycloak
  version: 0.0.5
  name: keycloak
  values:
  - jx-values.yaml
  - values.yaml
templates: {}
renderedvalues: {}
