apiVersion: kubernetes-client.io/v1	
kind: ExternalSecret	
metadata:	
  name: aws-credentials
spec:	
  backendType: vault	
  vaultMountPoint: kubernetes	
  vaultRole: jx-vault
  data:
    - name: AWS_ACCESS_KEY_ID
      key: secret/data/pipelines/aws
      property: accessKeyId
    - name: AWS_SECRET_ACCESS_KEY
      key: secret/data/pipelines/aws
      property: secretAccessKey
