apiVersion: kubernetes-client.io/v1	
kind: ExternalSecret	
metadata:	
  name: npmrc
spec:	
  backendType: vault	
  vaultMountPoint: kubernetes	
  vaultRole: jx-vault
  data:
    - name: .npmrc
      key: secret/data/npm
      property: .npmrc
