apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: oauth2proxy
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secret-infra
  data:
  - name: cookieSecret
    key: secret/data/{{ .Values.secretPaths.oauth2proxy }}
    property: cookieSecret
