apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secret-infra
  data:
  - name: POSTGRES_DATABASE
    key: secret/data/{{ .Values.secretPaths.keycloakDB }}
    property: database
  - name: POSTGRES_EXTERNAL_ADDRESS
    key: secret/data/{{ .Values.secretPaths.keycloakDB }}
    property: externalAddress
  - name: POSTGRES_EXTERNAL_PORT
    key: secret/data/{{ .Values.secretPaths.keycloakDB }}
    property: externalPort
  - name: POSTGRES_HOST
    key: secret/data/{{ .Values.secretPaths.keycloakDB }}
    property: host
  - name: POSTGRES_PASSWORD
    key: secret/data/{{ .Values.secretPaths.keycloakDB }}
    property: password
  - name: POSTGRES_SUPERUSER
    key: secret/data/{{ .Values.secretPaths.keycloakDB }}
    property: superuser
  - name: POSTGRES_USERNAME
    key: secret/data/{{ .Values.secretPaths.keycloakDB }}
    property: username
  
