apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: auth-keycloak-postgresql
spec:
  teamId: auth
  volume:
    size: 8Gi
  numberOfInstances: 1
  users:
    admin:  # database owner
    - superuser
    - createdb
    keycloak: []
  databases:
    keycloak: keycloak
  enableLogicalBackup: false
  postgresql:
    version: "13"
  enableShmVolume: true