apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-http
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: keycloak
    component: keycloak
  sessionAffinity: None
  type: ClusterIP