apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Scheduler
metadata:
  name: in-repo
spec:
  approve:
    issue_required: false
    lgtm_acts_as_approve: true
    require_self_approval: true
  merger:
    blocker_label: ""
    max_goroutines: 0
    merge_method: merge
    policy:
      from-branch-protection: true
      optional-contexts: {}
      required-contexts: {}
      required-if-present-contexts: {}
      skip-unknown-contexts: false
    pr_status_base_url: ""
    squash_label: ""
    target_url: http://dashboard{{ .Requirements.ingress.namespaceSubDomain }}{{ .Requirements.ingress.domain
      }}
  # lets look in the source repository for trigger files
  in_repo: true
  plugins:
    entries:
    - approve
    - assign
    - blunderbuss
    - help
    - hold
    - lgtm
    - lifecycle
    - override
    - size
    - trigger
    - wip
    - heart
    - cat
    - dog
    - pony
  queries:
  - excludedBranches: {}
    included_branches: {}
    labels:
      entries:
      - approved
    milestone: ""
    missingLabels:
      entries:
      - do-not-merge
      - do-not-merge/hold
      - do-not-merge/work-in-progress
      - needs-ok-to-test
      - needs-rebase
    review_approved_required: false
  - excludedBranches: {}
    included_branches: {}
    labels:
      entries:
      - updatebot
    milestone: ""
    missingLabels:
      entries:
      - do-not-merge
      - do-not-merge/hold
      - do-not-merge/work-in-progress
      - needs-ok-to-test
      - needs-rebase
    review_approved_required: false
  policy:
    protect_tested: true
  schedulerAgent:
    agent: tekton
  trigger:
    ignore_ok_to_test: false
    join_org_url: ""
    only_org_members: false
    trusted_org: todo
  welcome:
  - message_template: Welcome
