filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: rbac-manager
repositories:
- name: fairwinds-stable
  url: https://charts.fairwinds.com/stable
releases:
- chart: fairwinds-stable/rbac-manager
  version: 1.8.1
  name: rbac-manager
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
