apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: nexus
    mandatory: true
    properties:
    - name: username
      question: nexus user name
      help: The username used to authenticate with nexus
      defaultValue: admin
    - name: password
      question: nexus password
      help: The password to authenticate with nexus
      minLength: 5
      maxLength: 41
      defaultValue: admin123
