apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: jx-boot
    jenkins-x.io/kind: jx-git-operator
spec:
  backoffLimit: 4
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: jx-boot
        jenkins-x.io/kind: jx-git-operator
    spec:
      initContainers:
      - args:
        - gitops
        - git
        - clone
        command:
        - jx
        env:
        - name: XDG_CONFIG_HOME
          value: /workspace/xdg_config
        image: gcr.io/jenkinsxio/jx-boot:3.1.88
        name: git-clone
        volumeMounts:
        - mountPath: /workspace
          name: workspace-volume
        workingDir: /workspace
      containers:
      - args:
        - make apply || make failed
        command:
        - /bin/sh
        - -c
        env:
        - name: XDG_CONFIG_HOME
          value: /workspace/xdg_config
        - name: JX_SECRET_SIDECAR
          value: gsm
        - name: JX_SECRET_TMP_DIR
          value: /workspace/source/.jx-secrets
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: gcr.io/jenkinsxio/jx-boot:3.1.88
        imagePullPolicy: Always
        name: job
        volumeMounts:
        - mountPath: /workspace
          name: workspace-volume
        workingDir: /workspace/source
      - command:
        - versionStream/src/wait-for-complete.sh
        image: google/cloud-sdk:slim
        imagePullPolicy: Always
        name: gsm
        volumeMounts:
        - mountPath: /workspace
          name: workspace-volume
        workingDir: /workspace/source
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      serviceAccountName: jx-boot-job
      terminationGracePeriodSeconds: 30
      volumes:
      - name: workspace-volume
        emptyDir: {}
