{{- $domain  := .Values.domain -}}
{{- $provider  := .Values.jxRequirements.cluster.provider -}}
{{- $gkeServiceAccountSecret  := .Values.gkeServiceAccountSecret -}}
{{- $awsRegion  := .Values.jxRequirements.cluster.region -}}
{{- $email  := .Values.jxRequirements.ingress.tls.email -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "wildcard-{{ $domain | replace "." "-" }}"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "{{ $email }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: "wildcard-{{ $domain | replace "." "-" }}"
    solvers:
    - selector:
        dnsNames:
        - "*.{{ $domain }}"
        - "{{ $domain }}"
      # ACME DNS-01 provider configurations
      dns01:
{{- if eq $provider "gke" }}
        cloudDNS:
          # The project in which to update the DNS zone
          project: "{{ .Values.jxRequirements.cluster.project }}"
{{- if $gkeServiceAccountSecret }}
          # A secretKeyRef to a google cloud json service account
          serviceAccountSecretRef:
            name: {{ $gkeServiceAccountSecret }}
            key: credentials.json
{{- end }}
{{- end }}
{{- if eq $provider "eks" }}
        route53:
          region: {{ $awsRegion }}
{{- end }}