{{- $domain  := .Values.domain -}}
{{- range $subdomain := .Values.subdomains }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-wildcard-{{ $subdomain | replace "." "-" }}-{{ $domain | replace "." "-" }}"
  labels:
    jenkins.io/letsencrypt-service: production
spec:
  secretName: "tls-wildcard-{{ $subdomain | replace "." "-" }}-{{ $domain | replace "." "-" }}"
  issuerRef:
    name: "wildcard-{{ $subdomain | replace "." "-" }}-{{ $domain | replace "." "-" }}"
    kind: ClusterIssuer
  commonName: "*.{{ $subdomain }}.{{ $domain }}"
  dnsNames:
  - "*.{{ $subdomain }}.{{ $domain }}"
  - "{{ $subdomain }}.{{ $domain }}"
{{- end }}
