{{- $domain  := .Values.domain -}}
{{- $istioApiVersion  := .Values.istio.apiVersion -}}
{{- range $subdomain := .Values.subdomains }}
---
apiVersion: {{ $istioApiVersion }}
kind: Gateway
metadata:
  name: "wildcard-{{ $subdomain.name | replace "." "-" }}-{{ $domain | replace "." "-" }}"
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - hosts:
    - "*.{{ $subdomain.name }}.{{ $domain }}"
{{- if $subdomain.hosts }}
{{- range $host := $subdomain.hosts }}
    - {{ $host }}.{{ $subdomain.name }}.{{ $domain }}
{{- end }}
{{- end }}
    port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - "*.{{ $subdomain.name }}.{{ $domain }}"
{{- if $subdomain.hosts }}
{{- range $host := $subdomain.hosts }}
    - {{ $host }}.{{ $subdomain.name }}.{{ $domain }}
{{- end }}
{{- end }}
    port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      credentialName: "tls-wildcard-{{ $subdomain.name | replace "." "-" }}-{{ $domain | replace "." "-" }}"
      mode: SIMPLE
{{- end }}