{{- $domain  := .Values.domain -}}
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-main
spec:
  profile: default
  tag: 1.8.1
  values:
    global:
      proxy:
        autoInject: enabled
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            external-dns.alpha.kubernetes.io/hostname: >-
              *.{{ $domain }}{{- range $subdomain := .Values.subdomains }},*.{{ $subdomain.name }}.{{ $domain }}{{- end }}
      - name: cluster-local-gateway
        enabled: true
        label:
          istio: cluster-local-gateway
          app: cluster-local-gateway
        k8s:
          service:
            type: ClusterIP
            ports:
            - port: 15020
              name: status-port
            - port: 80
              targetPort: 8080
              name: http2
            - port: 443
              targetPort: 8443
              name: https