apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  defaults:
    backendType: vault
  secrets:
  - backendType: vault
    mappings:
    - key: secret/data/lighthouse/hmac
      name: hmac
      property: token
    name: lighthouse-hmac-token
  - backendType: vault
    mappings:
    - key: secret/data/lighthouse/oauth
      name: oauth
      property: token
    name: lighthouse-oauth-token
  - backendType: vault
    mappings:
    - key: secret/data/jx/pipelineUser
      name: username
      property: username
    - key: secret/data/jx/pipelineUser
      name: password
      property: token
    name: jx-pipeline-git-github-github
  - backendType: vault
    mappings:
    - key: secret/data/jx/pipelineUser
      name: username
      property: username
    - key: secret/data/jx/pipelineUser
      name: password
      property: token
    name: tekton-git
  - backendType: vault
    mappings:
    - key: secret/data/jx/pipelineUser
      name: username
      property: username
    - key: secret/data/jx/pipelineUser
      name: password
      property: token
    name: knative-git-user-pass
  - backendType: vault
    mappings:
    - key: secret/data/jx/docker
      name: username
      property: username
    - key: secret/data/jx/docker
      name: password
      property: password
    - key: secret/data/jx/docker
      name: email
      property: email
    - key: secret/data/jx/docker
      name: host
      property: host
    name: knative-docker-user-pass
  - backendType: vault
    mappings:
    - key: secret/data/nexus
      name: password
      property: password
    name: nexus
  - backendType: vault
    mappings:
    - key: secret/data/jx/adminUser
      name: BASIC_AUTH_USER
      property: username
    - key: secret/data/jx/adminUser
      name: BASIC_AUTH_PASS
      property: password
    name: jenkins-x-bucketrepo
  - backendType: vault
    mappings:
    - key: secret/data/jx/adminUser
      name: BASIC_AUTH_USER
      property: username
    - key: secret/data/jx/adminUser
      name: BASIC_AUTH_PASS
      property: password
    name: jenkins-x-chartmuseum
  - backendType: vault
    mappings:
    - key: secret/data/jx/mavenSettings
      name: settings.xml
      property: settingsXml
    - key: secret/data/jx/mavenSettings
      name: settings-security.xml
      property: securityXml
    name: jenkins-maven-settings
  - backendType: vault
    mappings:
    - key: secret/data/externaldns
      name: azure.json
      property: azure.json
    name: external-dns
  - backendType: vault
    mappings:
    - key: secret/data/monitor/grafana
      name: admin-user
      property: admin-user
    - key: secret/data/monitor/grafana
      name: admin-password
      property: admin-password
    - key: secret/data/monitor/grafana
      name: ldap-toml
      property: ldap-toml
    name: kube-prometheus-stack-grafana
  - backendType: vault
    mappings:
    - key: secret/data/monitor/alertmanager
      name: alertmanager.yaml
      property: alertmanager.yaml
    name: alertmanager-kube-prometheus-stack-alertmanager
  - backendType: vault
    mappings:
    - key: secret/data/monitor/loki
      name: loki.yaml
      property: loki.yaml
    name: loki-stack
  - backendType: vault
    mappings:
    - key: secret/data/auth/redis
      name: redis-password
      property: redis-password
    name: auth-redis
