apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  secrets:
  - name: lighthouse-hmac-token
    backendType: vault
    mappings:
    - name: hmac
      key: secret/data/lighthouse/hmac
      property: token
  - name: lighthouse-oauth-token
    backendType: vault
    mappings:
    - name: oauth
      key: secret/data/lighthouse/oauth
      property: token
  - name: jx-pipeline-git-github-github
    backendType: vault
    mappings:
    - name: username
      key: secret/data/jx/pipelineUser
      property: username
    - name: password
      key: secret/data/jx/pipelineUser
      property: token
  - name: tekton-git
    backendType: vault
    mappings:
    - name: username
      key: secret/data/jx/pipelineUser
      property: username
    - name: password
      key: secret/data/jx/pipelineUser
      property: token
  - name: knative-git-user-pass
    backendType: vault
    mappings:
    - name: username
      key: secret/data/jx/pipelineUser
      property: username
    - name: password
      key: secret/data/jx/pipelineUser
      property: token
  - name: knative-docker-user-pass
    backendType: vault
    mappings:
    - key: secret/data/jx/docker
      name: username
      property: username
    - key: secret/data/jx/docker
      name: password
      property: password
    - key: secret/data/jx/docker
      name: email
      property: email
    - key: secret/data/jx/docker
      name: host
      property: host
  - name: nexus
    backendType: vault
    mappings:
    - name: password
      key: secret/data/nexus
      property: password
  - name: jenkins-x-bucketrepo
    backendType: vault
    mappings:
    - name: BASIC_AUTH_USER
      key: secret/data/jx/adminUser
      property: username
    - name: BASIC_AUTH_PASS
      key: secret/data/jx/adminUser
      property: password
  - name: jenkins-x-chartmuseum
    backendType: vault
    mappings:
    - name: BASIC_AUTH_USER
      key: secret/data/jx/adminUser
      property: username
    - name: BASIC_AUTH_PASS
      key: secret/data/jx/adminUser
      property: password
  - name: jenkins-maven-settings
    backendType: vault
    mappings:
    - name: settings.xml
      key: secret/data/jx/mavenSettings
      property: settingsXml
    - name: settings-security.xml
      key: secret/data/jx/mavenSettings
      property: securityXml
  - name: external-dns
    backendType: vault
    mappings:
    - name: azure.json
      key: secret/data/externaldns
      property: azure.json
  - backendType: vault
    mappings:
    - key: secret/data/monitor/grafana
      name: admin-user
      property: admin-user
    - key: secret/data/monitor/grafana
      name: admin-password
      property: admin-password
    - key: secret/data/monitor/grafana
      name: ldap-toml
      property: ldap-toml
    name: kube-prometheus-stack-grafana
  - backendType: vault
    mappings:
    - key: secret/data/monitor/alertmanager
      name: alertmanager.yaml
      property: alertmanager.yaml
    name: alertmanager-kube-prometheus-stack-alertmanager
  - backendType: vault
    mappings:
    - key: secret/data/monitor/loki
      name: loki.yaml
      property: loki.yaml
    name: loki-stack
  - backendType: vault
    mappings:
    - key: secret/data/auth/redis
      name: redis-password
      property: redis-password
    name: auth-redis
  defaults:
    backendType: vault