apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: external-dns
    mandatory: true
    properties:
    - name: azure.json
      key: secret/data/externaldns
      question: enter a valid external-dns secret for the Azure DNS provider
      help: for secret details see https://github.com/kubernetes-sigs/external-dns#deploying-to-a-cluster
      template: |-
        {
        {{- if and (eq .Requirements.cluster.provider "aks") (hasKey .Requirements.cluster "azure") }}
        {{- if hasKey .Requirements.cluster.azure "dns" }}
          "resourceGroup": {{ .Requirements.cluster.azure.dns.resourceGroup }},
          "subscriptionId": {{ .Requirements.cluster.azure.dns.subscriptionId }},
          "tenantId": {{ .Requirements.cluster.azure.dns.tenantId }},
          "useManagedIdentityExtension": true
        {{- end }}
        {{- end }}
        }
