filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: kube-system
repositories:
- name: autoscaler
  url: https://kubernetes.github.io/autoscaler
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: descheduler
  url: https://kubernetes-sigs.github.io/descheduler/
releases:
# - chart: autoscaler/cluster-autoscaler  # uncomment for AWS
#   version: 9.9.2
#   name: cluster-autoscaler
#   values:
#   - jx-values.yaml
#   - values.cluster-autoscaler.yaml
- chart: bitnami/metrics-server
  version: 5.5.1
  name: metrics-server
  values:
  - jx-values.yaml
  - values.metrics-server.yaml
- chart: descheduler/descheduler
  version: 0.20.0
  name: descheduler
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
