filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: kube-system
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
- chart: bitnami/metrics-server
  version: 5.3.4
  name: metrics-server
  values:
  - jx-values.yaml
  - values.metrics-server.yaml
templates: {}
renderedvalues: {}
