apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: slack-token
    mandatory: true
    properties:
    - name: token
      key: secret/data/jx/slack
      question: the slack token
      help: the token to connect to slack
