filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-vault
repositories:
- name: external-secrets
  url: https://external-secrets.github.io/kubernetes-external-secrets
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
releases:
- chart: external-secrets/kubernetes-external-secrets
  version: 6.3.0
  name: kubernetes-external-secrets
  values:
  - ../../versionStream/charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/pusher-wave
  version: 0.4.16
  name: pusher-wave
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
