apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: jx-pipelines-visualizer-authorization-jwt
spec:
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
  selector:
    matchLabels:
      app.kubernetes.io/name: jx-pipelines-visualizer