apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jx-pipelines-visualizer-authentication-jwt
spec:
  jwtRules:
  - issuer: https://{{ .Values.keycloak.url }}/auth/realms/{{ .Values.keycloak.realm }}
    jwksUri: https://{{ .Values.keycloak.url }}/auth/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/certs
    forwardOriginalToken: true
    outputPayloadToHeader: x-jwt-payload
  selector:
    matchLabels:
      app.kubernetes.io/name: jx-pipelines-visualizer