filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: stable
  url: https://charts.helm.sh/stable
releases:
- chart: bitnami/external-dns
  version: 4.5.1
  condition: jxRequirementsIngressExternalDNS.enabled
  name: external-dns
  values:
  - ../../versionStream/charts/bitnami/external-dns/values.yaml.gotmpl
  - jx-values.yaml
  - values.external-dns.yaml
- chart: jenkins-x/jxboot-helmfile-resources
  version: 1.0.27
  name: jxboot-helmfile-resources
  values:
  - ../../versionStream/charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
  - values.jxboot-helmfile-resources.yaml
- chart: jx3/jenkins-x-crds
  version: 3.0.5
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jx3/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/jx-pipelines-visualizer
  version: 1.0.3
  name: jx-pipelines-visualizer
  values:
  - ../../versionStream/charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
  - jx-values.yaml
  - values.dashboard.yaml
- chart: jx3/jx-preview
  version: 0.0.143
  name: jx-preview
  values:
  - jx-values.yaml
  - values.preview.yaml
- chart: jenkins-x/lighthouse
  version: 0.0.913
  name: lighthouse
  values:
  - ../../versionStream/charts/jenkins-x/lighthouse/values.yaml.gotmpl
  - jx-values.yaml
  - values.lighthouse.yaml
- chart: jx3/jx-build-controller
  version: 0.0.25
  name: jx-build-controller
  values:
  - ../../versionStream/charts/jx3/jx-build-controller/values.yaml.gotmpl
  - jx-values.yaml
- chart: jenkins-x/bucketrepo
  version: 0.1.53
  name: bucketrepo
  values:
  - ../../versionStream/charts/jenkins-x/bucketrepo/values.yaml.gotmpl
  - jx-values.yaml
- chart: ./charts/jx-istio
  version: 0.0.1
  name: jx-istio
  values:
  - jx-values.yaml
  - values.istio.yaml
templates: {}
renderedvalues: {}
