filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: stable
  url: https://charts.helm.sh/stable
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: bitnami/external-dns
  version: 5.1.3
  condition: jxRequirementsIngressExternalDNS.enabled
  name: external-dns
  values:
  - ../../versionStream/charts/bitnami/external-dns/values.yaml.gotmpl
  - jx-values.yaml
  - values.external-dns.yaml
- chart: jx3/jxboot-helmfile-resources
  version: 1.0.64
  name: jxboot-helmfile-resources
  values:
  - ../../versionStream/charts/jx3/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
  - values.jxboot-helmfile-resources.yaml
- chart: jx3/jenkins-x-crds
  version: 3.0.7
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jx3/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/jx-pipelines-visualizer
  version: 1.7.1
  name: jx-pipelines-visualizer
  values:
  - ../../versionStream/charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
  - jx-values.yaml
  - values.dashboard.yaml
- chart: jxgh/jx-preview
  version: 0.0.182
  name: jx-preview
  values:
  - jx-values.yaml
  - values.preview.yaml
- chart: jx3/lighthouse
  version: 1.1.10
  name: lighthouse
  values:
  - ../../versionStream/charts/jx3/lighthouse/values.yaml.gotmpl
  - jx-values.yaml
  - values.lighthouse.yaml.gotmpl
- chart: jx3/jx-build-controller
  version: 0.3.1
  name: jx-build-controller
  values:
  - ../../versionStream/charts/jx3/jx-build-controller/values.yaml.gotmpl
  - jx-values.yaml
- chart: ./charts/jx-istio
  version: 0.0.1
  name: jx-istio
  values:
  - jx-values.yaml
  - values.istio.yaml
- chart: ./charts/pipeline-secrets
  version: 1.0.0
  name: pipeline-secrets
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
