apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  defaults:
    backendType: gcpSecretsManager
  secrets:
  - backendType: gcpSecretsManager
    mappings:
    - key: lighthouse-hmac
      name: hmac
      property: token
    name: lighthouse-hmac-token
  - backendType: gcpSecretsManager
    mappings:
    - key: lighthouse-oauth
      name: oauth
      property: token
    name: lighthouse-oauth-token
  - backendType: gcpSecretsManager
    mappings:
    - key: jx-pipeline-user
      name: username
      property: username
    - key: jx-pipeline-user
      name: password
      property: token
    name: jx-pipeline-git-github-github
  - backendType: gcpSecretsManager
    mappings:
    - key: jx-pipeline-user
      name: username
      property: username
    - key: jx-pipeline-user
      name: password
      property: token
    name: knative-git-user-pass
  - backendType: gcpSecretsManager
    mappings:
    - key: jx-docker
      name: username
      property: username
    - key: jx-docker
      name: password
      property: password
    name: knative-docker-user-pass
  - backendType: gcpSecretsManager
    mappings:
    - key: jx-admin-user
      name: password
      property: password
    name: nexus
  - backendType: gcpSecretsManager
    mappings:
    - name: BASIC_AUTH_USER
      key: nexus
      property: username
    - name: BASIC_AUTH_PASS
      key: nexus
      property: password
    name: jenkins-x-bucketrepo
  - backendType: gcpSecretsManager
    mappings:
    - key: jx-admin-user
      name: BASIC_AUTH_USER
      property: username
    - key: jx-admin-user
      name: BASIC_AUTH_PASS
      property: password
    name: jenkins-x-chartmuseum
  - backendType: gcpSecretsManager
    mappings:
    - key: jx-maven-settings
      name: settings.xml
      property: settingsXml
    - key: jx-maven-settings
      name: settings-security.xml
      property: securityXml
    name: jenkins-maven-settings
