filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: istio-system
repositories:
- name: kiali
  url: https://kiali.org/helm-charts
releases:
- chart: ./charts/istio-system
  version: 1.6.0
  name: istio-system
  values:
  - jx-values.yaml
  - values.yaml
templates: {}
renderedvalues: {}
