filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: istio-system
repositories:
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
releases:
- chart: ./charts/istio-system
  version: 1.1.0
  name: istio-system
  values:
  - jx-values.yaml
  - values.yaml
templates: {}
renderedvalues: {}
