apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: test
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          resources: {}
          volumeMounts:
          - mountPath: /etc/podinfo
            name: podinfo
            readOnly: true
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
        - image: ghcr.io/jenkins-x/jx:3.2.152
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx gitops variables
        - env:
          - name: GH_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                key: password
                name: bdd-git-gitlab
          image: ghcr.io/jenkins-x/jx:3.2.152
          name: runci
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh
            echo running bdd test $JOB_NAME
            /workspace/source/.lighthouse/jenkins-x/bdd/$JOB_NAME/ci.sh
        volumes:
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
          name: podinfo
  podTemplate: {}
  serviceAccountName: bdd-bot
  timeout: 240h0m0s
status: {}
