apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: grafana
    mandatory: true
    properties:
    - name: admin-user
      key: secret/data/grafana/adminUser
      question: the pipeline username
      help: the user to login to Grafana
      defaultValue: admin
    - name: admin-password
      key: secret/data/grafana/adminPassword
      question: admin passowrd for grafana
      help: the password to login to Grafana
      generator: password
