apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/60bed6408732c1eda91a15713f51a9f97dcb1757/tasks/git-clone/git-clone.yaml
  name: release
spec:
  pipelineSpec:
    params:
    - default: master
      description: git revision to checkout (branch, tag, sha, ref…)
      name: revision
      type: string
    tasks:
    - name: from-build-pack
      params:
      - name: revision
        value: $(params.revision)
      resources: {}
      taskSpec:
        metadata: {}
        params:
        - default: master
          description: git revision to checkout (branch, tag, sha, ref…)
          name: revision
          type: string
        stepTemplate:
          env:
          - name: PIPELINE_KIND
            value: release
          - name: JX_BATCH_MODE
            value: "true"
          - name: VERSION
            value: $(inputs.params.version)
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/jx-cli:3.1.88
          name: admin-log
          script: |
            #!/usr/bin/env sh
            echo "viewing the git operator boot job log for commit sha: $PULL_BASE_SHA"
            jx admin log --commit-sha $PULL_BASE_SHA
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
