apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: auth
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - hosts:
{{- if .Values.gateway.hosts }}
  {{- range .Values.gateway.hosts }}
    - {{.}}
  {{- end }}
{{- end}}
    port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
{{- if .Values.gateway.hosts }}
  {{- range .Values.gateway.hosts }}
    - {{.}}
  {{- end }}
{{- end}}
    port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      credentialName: {{ .Values.gateway.tlsCertSecret }}
      mode: SIMPLE