apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak
spec:
  hosts:
  - auth.example.com
  gateways:
  - auth
  http:
  - route:
    - destination:
        port:
          number: 8443
        host: keycloak
