apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
spec:
  hosts:
  - auth.example.com
  gateways:
  - istio-system/wildcard-example-com
  http:
  - route:
    - destination:
        port:
          number: 8080
        host: keycloak-http
